# -*- coding: utf-8 -*-
"""Proyek Akhir_Machine Learning Terapan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10H4xp6aDkV6prp21nHkxRQ2p-wrd4cHw

# Sistem Rekomendasi Lagu Spotify 🎵

Notebook ini membangun sistem rekomendasi musik berdasarkan data Spotify track dengan dua pendekatan utama:

1. **Content-Based Filtering**: merekomendasikan lagu yang mirip berdasarkan fitur seperti danceability, energy, valence, dll.
2. **Collaborative Filtering** *(jika tersedia)*: merekomendasikan lagu berdasarkan perilaku pengguna.

## 🎯 Tujuan
- Membuat sistem rekomendasi lagu yang dipersonalisasi.
- Memberikan saran lagu baru yang kemungkinan disukai oleh pengguna.
- Menunjukkan bagaimana dua pendekatan berbeda bekerja pada dataset Spotify.

Dataset: [Spotify Tracks Dataset](https://www.kaggle.com/datasets/maharshipandya/-spotify-tracks-dataset)

# Import
"""

# Import library untuk analisis data dan visualisasi
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

# Untuk machine learning dan preprocessing
from sklearn.preprocessing import StandardScaler
from sklearn.metrics.pairwise import cosine_similarity

# Untuk menampilkan semua kolom
pd.set_option('display.max_columns', None)

"""import semua library"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("maharshipandya/-spotify-tracks-dataset")

print("Path to dataset files:", path)

"""download dataset menggunakan path kaggle hub"""

print(os.listdir(path))

"""melihat list dataset yang sudah di download"""

tracks_file_path = os.path.join(path, 'dataset.csv')
df = pd.read_csv(tracks_file_path)

"""mengambil dataset dan menginisiasi dataset menjadi df"""

# Ambil sampel 20.000 baris secara acak
df = df.sample(n=20000, random_state=42).reset_index(drop=True)
print("Ukuran dataset setelah disampling:", df.shape)

"""mengambil 20000 sample dataset untuk meminimalisir running time"""

df.head()

"""melihat 5 data teratas

# Data Understanding
"""

df.info()

"""terdapat 20 kolom variabel yang memiliki kurang lebih 20000 sample yang memiliki tipe beragam"""

# Menampilkan semua kolom dan tipe data
df.columns, df.dtypes

"""Cell ini digunakan untuk menampilkan seluruh kolom beserta tipe datanya pada dataset df, yang membantu dalam memahami struktur data sebelum dilakukan pemrosesan atau pemodelan. Informasi ini penting untuk menentukan kolom mana yang bersifat numerik (untuk filtering), kategorik, atau tidak relevan.

Penjelasan Variabel Penting:
- track_id, track_name, artists: identitas lagu.
- popularity, duration_ms, explicit: informasi umum lagu.
- danceability, energy, loudness, speechiness, acousticness, instrumentalness, liveness, valence, tempo: fitur audio numerik, berguna untuk content-based filtering.
- track_genre: kategori genre lagu.
- Unnamed: 0: kolom indeks hasil import, sebaiknya dihapus.
"""

# Menghapus kolom indeks duplikat (jika ada)
if 'Unnamed: 0' in df.columns:
    df.drop(columns=['Unnamed: 0'], inplace=True)

"""menghapus tabel Unnamed: 0"""

# Cek nilai kosong
missing_summary = df.isnull().sum()
print("Jumlah nilai kosong per kolom:\n", missing_summary)

# Jika ada kolom dengan missing value, drop baris tersebut
df_clean = df.dropna()

# Konfirmasi data setelah dibersihkan
print("\nSetelah menghapus missing value:")
print(df_clean.info())

"""menghapus nilai null dan kembali melakukan pengecekan kepada df_clean"""

# Hapus duplikasi berdasarkan 'track_id' atau kombinasi unik track
before = df_clean.shape[0]
df_clean.drop_duplicates(subset=['track_id'], inplace=True)
after = df_clean.shape[0]

print(f"Duplikasi yang dihapus: {before - after}")

"""menghapus data duplikat yang berjumlah 1039

# Content-Based Filtering
"""

# Pilih fitur audio numerik
audio_features = [
    'danceability', 'energy', 'key', 'loudness', 'mode',
    'speechiness', 'acousticness', 'instrumentalness',
    'liveness', 'valence', 'tempo'
]

# Cek fitur yang tersedia
available_features = [col for col in audio_features if col in df_clean.columns]
print("Fitur yang tersedia untuk rekomendasi:", available_features)

# Normalisasi data numerik
scaler = StandardScaler()
feature_matrix = scaler.fit_transform(df_clean[available_features])

# Gabungkan kembali dengan info lagu
df_features = pd.DataFrame(feature_matrix, columns=available_features)
df_features['track_name'] = df_clean['track_name'].values
df_features['artists'] = df_clean['artists'].values

df_features.head()

"""Cell ini digunakan untuk menyiapkan fitur numerik dari lagu-lagu yang relevan untuk sistem rekomendasi berbasis konten. Pertama, fitur-fitur audio seperti danceability, energy, valence, dan lainnya dipilih dan difilter agar hanya mencakup kolom yang tersedia dalam dataset. Setelah itu, fitur-fitur tersebut dinormalisasi menggunakan StandardScaler agar berada pada skala yang sama, sehingga perhitungan kemiripan antar lagu menjadi lebih akurat. Hasil akhir disimpan dalam DataFrame df_features yang memuat fitur numerik beserta informasi track_name dan artists."""

# Hitung cosine similarity antar lagu berdasarkan fitur
cosine_sim = cosine_similarity(df_features[available_features])

# Buat DataFrame matrix similarity untuk referensi nama lagu
cosine_sim_df = pd.DataFrame(
    cosine_sim,
    index=df_features['track_name'],
    columns=df_features['track_name']
)

# Tampilkan sebagian
cosine_sim_df.iloc[:5, :5]

"""Cell ini digunakan untuk menghitung cosine similarity antar lagu berdasarkan fitur numerik seperti danceability, energy, dan lainnya yang sebelumnya sudah dinormalisasi. Perhitungan cosine similarity akan menghasilkan nilai antara -1 hingga 1 yang menunjukkan tingkat kemiripan antara dua lagu: semakin mendekati 1, semakin mirip."""

def recommend_tracks(track_name, top_n=5):
    if track_name not in cosine_sim_df.columns:
        return f"Lagu '{track_name}' tidak ditemukan dalam dataset."

    # Ambil skor similarity dan urutkan
    sim_scores = cosine_sim_df[track_name].sort_values(ascending=False)

    # Ambil top-n selain lagu itu sendiri
    recommended = sim_scores.iloc[1:top_n+1]

    # Gabungkan dengan nama artis dan buang duplikat
    recommendations = (
        df_features[df_features['track_name'].isin(recommended.index)]
        [['track_name', 'artists']]
        .drop_duplicates()
        .reset_index(drop=True)
    )

    return recommendations

recommend_tracks("Failed Organum", top_n=5)

"""Fungsi recommend_tracks() digunakan untuk menghasilkan rekomendasi lagu yang mirip dengan lagu input berdasarkan kemiripan fitur numerik audio (seperti danceability, energy, dll) menggunakan cosine similarity. Fungsi ini memastikan input lagu tersedia dalam dataset, menghitung kemiripan dengan semua lagu lain, lalu mengambil top_n lagu yang paling mirip (selain lagu itu sendiri). Hasilnya disajikan dalam bentuk DataFrame yang berisi nama lagu dan artis, serta telah difilter agar tidak ada duplikat.


"""

# Coba rekomendasi untuk beberapa lagu populer
print("🎶 Rekomendasi untuk 'I'm Ready - Radio Edit':")
display(recommend_tracks("I'm Ready - Radio Edit", 5))

print("🎶 Rekomendasi untuk 'Into Your Arms (feat. Ava Max)':")
display(recommend_tracks("Photograph", 5))

"""melakukan tes kepada lagu untuk menghasilkan rekomendasi

# Collaborative Filtering
"""

# Lihat semua kolom untuk mencari tahu apakah ada user-rating/interaksi
df_clean.columns

"""melihat seluruh kolom dari df_clean"""

import random

# Ambil subset track untuk efisiensi
track_subset = df_clean[['track_id', 'track_name']].drop_duplicates().sample(500, random_state=42)

# Simulasikan 50 pengguna
user_ids = [f"user_{i}" for i in range(1, 51)]

# Simulasikan rating antar user dan lagu
simulated_data = []

for user in user_ids:
    # Tiap user rating 10-30 lagu acak
    rated_tracks = track_subset.sample(random.randint(10, 30))
    for _, row in rated_tracks.iterrows():
        simulated_data.append({
            'user_id': user,
            'track_id': row['track_id'],
            'rating': random.randint(1, 5)
        })

df_ratings = pd.DataFrame(simulated_data)
df_ratings.head()

"""Cell ini digunakan untuk mensimulasikan data interaksi antara pengguna dan lagu karena dataset asli tidak memiliki informasi rating pengguna. Sebanyak 50 pengguna fiktif dibuat, dan masing-masing diberi tugas memberikan rating acak (antara 1 hingga 5) untuk 10–30 lagu yang dipilih secara acak dari 500 lagu sampel. Hasilnya disimpan dalam DataFrame `df_ratings`, yang terdiri dari `user_id`, `track_id`, dan `rating`, dan akan digunakan sebagai input untuk model collaborative filtering.

"""

# !pip install numpy==1.24.4

# !pip install scikit-surprise

"""install scikit_surprise"""

from surprise import Dataset, Reader, KNNBasic
from surprise.model_selection import train_test_split
from surprise import accuracy

# Setup Surprise Dataset
reader = Reader(rating_scale=(1, 5))
data = Dataset.load_from_df(df_ratings[['user_id', 'track_id', 'rating']], reader)

# Train-test split
trainset, testset = train_test_split(data, test_size=0.2, random_state=42)

# Model Collaborative Filtering: User-based
algo = KNNBasic(sim_options={'user_based': True})
algo.fit(trainset)

# Prediksi dan evaluasi
predictions = algo.test(testset)
print("RMSE:", accuracy.rmse(predictions))

"""Cell ini digunakan untuk membangun dan mengevaluasi model **Collaborative Filtering berbasis pengguna** menggunakan library Surprise. Dataset `df_ratings` yang berisi `user_id`, `track_id`, dan `rating` diubah menjadi format Surprise, lalu dibagi menjadi data latih dan uji. Model `KNNBasic` digunakan dengan parameter `user_based=True`, artinya rekomendasi dihitung berdasarkan kemiripan antar pengguna. Setelah pelatihan, model dievaluasi menggunakan RMSE, yang menunjukkan seberapa baik model memprediksi rating yang belum diketahui.

"""

def get_recommendations_for_user(user_id, top_n=5):
    all_track_ids = df_ratings['track_id'].unique()
    rated_by_user = df_ratings[df_ratings['user_id'] == user_id]['track_id'].tolist()

    # Lagu yang belum dirating oleh user
    unrated = [track for track in all_track_ids if track not in rated_by_user]

    # Prediksi rating
    predictions = [algo.predict(user_id, track_id) for track_id in unrated]
    predictions.sort(key=lambda x: x.est, reverse=True)

    # Ambil top-n prediksi tertinggi
    top_predictions = predictions[:top_n]
    top_track_ids = [pred.iid for pred in top_predictions]

    recommended_tracks = df_clean[df_clean['track_id'].isin(top_track_ids)][['track_name', 'artists']].drop_duplicates()
    return recommended_tracks.reset_index(drop=True)

# Contoh rekomendasi
get_recommendations_for_user("user_10", top_n=5)

"""Fungsi `get_recommendations_for_user()` digunakan untuk menghasilkan rekomendasi lagu bagi pengguna tertentu berdasarkan hasil prediksi rating dari model collaborative filtering. Fungsi ini terlebih dahulu mengidentifikasi lagu-lagu yang belum pernah dirating oleh pengguna tersebut, lalu memprediksi rating untuk setiap lagu menggunakan model `algo`. Prediksi kemudian diurutkan berdasarkan skor estimasi tertinggi, dan lima lagu teratas diambil sebagai hasil rekomendasi. Output yang ditampilkan berupa nama lagu dan artis, diambil dari `df_clean` berdasarkan `track_id` yang direkomendasikan.

"""

# Contoh input lagu untuk content-based
content_input = "I'm Ready - Radio Edit"

# Rekomendasi dari content-based
content_recs = recommend_tracks(content_input, top_n=5)
if isinstance(content_recs, pd.DataFrame):
    content_recs['source'] = 'Content-Based'
else:
    print("Content-based error:", content_recs)
    content_recs = pd.DataFrame(columns=['track_name', 'artists', 'source'])

# Rekomendasi dari collaborative filtering
collab_recs = get_recommendations_for_user("user_10", top_n=5)
if isinstance(collab_recs, pd.DataFrame):
    collab_recs['source'] = 'Collaborative'
else:
    print("Collaborative filtering error:", collab_recs)
    collab_recs = pd.DataFrame(columns=['track_name', 'artists', 'source'])


# Gabungkan hasil
combined_recs = pd.concat([content_recs, collab_recs], ignore_index=True)

# Tampilkan
combined_recs

"""Cell ini bertujuan untuk menggabungkan hasil rekomendasi dari dua pendekatan: content-based filtering dan collaborative filtering. Lagu yang mirip dengan input lagu "I'm Ready - Radio Edit" direkomendasikan melalui fungsi recommend_tracks, sementara lagu yang diprediksi paling disukai oleh pengguna "user_10" diperoleh dari get_recommendations_for_user. Masing-masing hasil diberi label sumber (Content-Based atau Collaborative) dan digabung menjadi satu DataFrame combined_recs untuk ditampilkan dan dibandingkan."""

# Hitung jumlah per sistem
plt.figure(figsize=(6, 4))
sns.countplot(data=combined_recs, x='source')
plt.title("Jumlah Lagu yang Direkomendasikan per Sistem")
plt.xlabel("Metode Rekomendasi")
plt.ylabel("Jumlah Lagu")
plt.show()

"""Cell ini menampilkan visualisasi jumlah lagu yang direkomendasikan oleh masing-masing metode—content-based dan collaborative filtering—dengan menggunakan grafik batang. Grafik ini membantu memvisualisasikan distribusi hasil rekomendasi dan dapat digunakan untuk membandingkan seberapa banyak lagu yang berhasil dihasilkan oleh masing-masing sistem. Perbedaan jumlah bisa terjadi jika misalnya ada duplikasi, data kosong, atau filter yang diterapkan saat menghasilkan rekomendasi.

## ✅ Kesimpulan Proyek Rekomendasi Lagu Spotify

Dalam proyek ini, telah dibangun dua jenis sistem rekomendasi:

1. **Content-Based Filtering**
   - Menggunakan fitur audio seperti danceability, energy, valence, dll.
   - Rekomendasi diberikan berdasarkan kemiripan konten lagu.

2. **Collaborative Filtering (User-Based)**
   - Menggunakan interaksi simulasi antara pengguna dan lagu.
   - Rekomendasi diberikan berdasarkan kesamaan perilaku antar pengguna.

### Hasil:
- Kedua sistem mampu menghasilkan rekomendasi yang relevan.
- Content-based cocok untuk pengguna baru (cold-start).
- Collaborative filtering sangat bergantung pada data interaksi.
"""