# -*- coding: utf-8 -*-
"""Proyek_Akhir_Machine_Learning_Terapan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16HkGBM-C5otuM7H0_ybxLtBn6NuNC7lZ

# Import
"""

# Import library untuk analisis data dan visualisasi
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

# Untuk machine learning dan preprocessing
from sklearn.preprocessing import StandardScaler
from sklearn.metrics.pairwise import cosine_similarity

# Untuk menampilkan semua kolom
pd.set_option('display.max_columns', None)

"""import semua library"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("parasharmanas/movie-recommendation-system")

print("Path to dataset files:", path)

"""download dataset melalui path kaggle

# Load Data
"""

print(os.listdir(path))

"""melihat list dataset"""

movies = pd.read_csv(os.path.join(path, 'movies.csv'))
ratings = pd.read_csv(os.path.join(path, 'ratings.csv'))

"""menginisiasi dataset mejadi variabel"""

print('Total film yang tersedia:', len(movies.movieId.unique()))
print('Total pengguna yang memberikan rating:', len(ratings.userId.unique()))

"""melihat total bedasarkan userID

# Data Understanding
"""

# informasi dataset movies
movies.info()

"""melihat info dari movies, terdapat 3 kolom dengan total 62423 row"""

# informasi dataset ratings
ratings.info()

"""melihat info dari ratings, terdapat 4 kolom dengan total 25000095 row"""

print('\nMissing values in movies dataset:')
print(movies.isnull().sum())

print('\nMissing values in ratings dataset:')
print(ratings.isnull().sum())

"""melihat nilai null dari movies dan ratings, tidak ada nilai null pada kedua dataset"""

# dataset movies
movies

"""melihat dataset movies"""

movies['year_of_release'] = movies.title.str.extract('([0-9]{4})')
movies.head()

"""Mengekstrak tahun rilis dari kolom title dan menyimpannya ke kolom baru 'year_of_release'

"""

# Mengubah tipe data kolom 'title' menjadi string
movies['title'] = movies['title'].astype(str)

# Menghapus informasi tahun (atau teks setelah tanda kurung buka) dari judul film
movies['title'] = movies['title'].str.split('(', n=1).str[0].str.strip()

movies.head()

"""melihat 5 row pertama pada dataset movies, mengekstrak tahun dari judul film dan membersihkan judul film"""

ratings

"""melihat dataset ratings"""

ratings.rating.unique()

ratings['rating'] = ratings['rating'].astype(float)

"""mengubah tipe menjadi float"""

ratings.timestamp = pd.to_datetime(ratings['timestamp'], unit='s')
ratings.head()

"""melihat 5 row pertama pada dataset ratings, melihat nilai unik, mengubah semua tipe menjadi float dan Konversi timestamp"""

# Menggabungkan dataframe movies dan ratings berdasarkan kolom 'movieId' dengan metode left join
films = pd.merge(movies, ratings, on='movieId', how='left')

# Menampilkan dataframe hasil penggabungan
films

"""menggabungkan dataset movies dan ratings menggunakan left join dengan movieId sebagai key value"""

import sys

# Set opsi cetak NumPy agar seluruh elemen array ditampilkan tanpa dipersingkat
np.set_printoptions(threshold=sys.maxsize)

# Cetak jumlah genre unik yang ada di kolom 'genres' pada dataframe films
print('Banyak genre films: ', len(films['genres'].unique()))

# Cetak daftar lengkap genre unik pada kolom 'genres'
print('Genre films: ', films['genres'].unique())

# Kembalikan opsi cetak NumPy ke pengaturan default
np.set_printoptions(threshold=None)

"""melakukan pengecekan genre unik"""

# show non-genre
films[films['genres'] == '(no genres listed)']

"""menampilkan film yang tidak punya genre"""

films = films.loc[films.genres != '(no genres listed)']
films.head()

"""menghapus film yang tidak punya genre

"""

films.groupby('movieId').sum(numeric_only=True)

"""Kelompokkan berdasarkan movieId"""

# Menghitung frekuensi kemunculan setiap movieId di dataframe films
get_values = films['movieId'].value_counts()

# Memilih movieId yang muncul setidaknya 50 kali
temp = get_values[get_values >= 50].index

# Memfilter dataframe films agar hanya menyimpan baris dengan movieId yang frekuensinya >= 50
films = films[films['movieId'].isin(temp)]

# Menampilkan dataframe hasil filter
films

"""Filter film dengan jumlah rating minimal 50"""

# duplicated by movieId
films.duplicated('movieId').sum()

"""melihat jumlah duplikat berdasarkan movieID. jumlahnya 24620127"""

# duplicated by title
films.duplicated('title').sum()

"""melihat jumlah duplikat berdasarkan movieID. jumlahnya 24620647"""

# drop duplicated data by movieId & title
films = films.drop_duplicates('movieId')
films = films.drop_duplicates('title')

"""Cek duplikasi berdasarkan movieId dan title lalu hapus duplikasi


"""

# Ganti string yang cocok dengan pola regex '[nS]ci-Fi' menjadi 'Scifi' di kolom 'genres'
films['genres'] = films['genres'].str.replace('[nS]ci-Fi', 'Scifi', regex=True)

films.head()

"""Ganti string yang cocok dengan pola regex '[nS]ci-Fi' menjadi 'Scifi' di kolom 'genres'

"""

# Membuat salinan dataframe films ke variabel preparation
preparation = films
preparation.sort_values(by='movieId').head()

"""Duplikasi dataframe ke preparation`"""

# Mengubah kolom 'movieId' pada dataframe preparation menjadi list
film_id = preparation['movieId'].to_list()

# Mengubah kolom 'title' pada dataframe preparation menjadi list
film_name = preparation['title'].to_list()

# Mengubah kolom 'genres' pada dataframe preparation menjadi list
film_genre = preparation['genres'].to_list()

# Menampilkan panjang masing-masing list
print(len(film_id))
print(len(film_name))
print(len(film_genre))

"""Buat list ID, nama, genre film

"""

# Membuat dataframe dari dictionary yang berisi list film_id, film_name, dan film_genre
df_film = pd.DataFrame(data={
    'film_id': film_id,
    'film_name': film_name,
    'genre': film_genre
})
df_film

"""Buat dataframe baru untuk TF-IDF"""

# data sample
data = df_film
data.head()

""" Data sample"""

from sklearn.feature_extraction.text import TfidfVectorizer

# Membuat objek TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer()

# Melatih model TF-IDF pada kolom 'genre' dari dataframe data
tfidf_vectorizer.fit(data['genre'])

# Mendapatkan daftar fitur (kata) yang dihasilkan oleh TfidfVectorizer
tfidf_vectorizer.get_feature_names_out()

"""Fit TF-IDF pada genre"""

# fit & transform to matrix
tfidf_matrix = tfidf_vectorizer.fit_transform(data['genre'])

# show matrix dimension
tfidf_matrix.shape

"""Transformasi TF-IDF"""

# Mengubah vektor tf-idf menjadi bentuk matriks padat (dense matrix)
tfidf_matrix.todense()

"""Lihat matriks padat"""

# Membuat dataframe dari matriks tf-idf dengan baris sebagai film_name dan kolom sebagai genre
pd.DataFrame(
    tfidf_matrix.todense(),
    columns=tfidf_vectorizer.get_feature_names_out(),
    index=data.film_name
).sample(n=20, axis=1).sample(n=10, axis=0)

"""Tampilkan sebagian besar matriks"""

print(tfidf_matrix.shape)
print(type(tfidf_matrix))

""" Info bentuk matriks"""

# total data
n = tfidf_matrix.shape[0]

# ambil 10000 indeks acak tanpa pengulangan
random_indices = np.random.choice(n, size=10000, replace=False)

# ambil subset sparse matrix berdasarkan indeks acak
subset_matrix = tfidf_matrix[random_indices]

# hitung cosine similarity pada subset acak ini
cosine_sim_subset = cosine_similarity(subset_matrix)

# contoh: film nama yang diambil sesuai index acak
subset_film_names = data.film_name.iloc[random_indices].tolist()

"""Sampling untuk cosine similarity"""

cosine_sim_df = pd.DataFrame(
    cosine_sim_subset,
    index=subset_film_names,
    columns=subset_film_names
)
print('Shape:', cosine_sim_df.shape)
cosine_sim_df.sample(5, axis=1).sample(10, axis=0)

"""Buat dataframe cosine similarity"""

# function recommendations
def film_recommendations(film_name, similarity_data=cosine_sim_df, items=data[['film_name', 'genre']], k=5):
    # urutkan skor kemiripan dari tinggi ke rendah (tanpa film itu sendiri)
    similarity_scores = similarity_data[film_name].sort_values(ascending=False)

    # ambil top-k+1 teratas karena termasuk film itu sendiri
    closest = similarity_scores.iloc[1:k+1].index

    # gabungkan dengan data film untuk mendapatkan genre
    return pd.DataFrame(closest, columns=['film_name']).merge(items).head(k)

"""Fungsi rekomendasi berdasarkan nama film"""

# sample data
data.sample(3)

data[data.film_name.eq('The Raid 2: Berandal')]

"""Cek film tertentu"""

film_recommendations('The Raid 2: Berandal')

"""Coba rekomendasi berdasarkan nama film"""

df = preparation
df

"""Simpan df preparation"""

# ubah nilai unik dari 'userId' menjadi list
user_ids = list(set(df['userId']))
print('list userID: ', user_ids)

# encode 'userId'
user_to_user_encoded = dict(zip(user_ids, range(len(user_ids))))
print('encoded userID : ', user_to_user_encoded)

# encoding index ke 'userId'
user_encoded_to_user = dict(zip(range(len(user_ids)), user_ids))
print('encoded angka ke userID: ', user_encoded_to_user)

"""Encode userId"""

# ubah nilai unik dari 'movieId' menjadi list
films_ids = list(set(df['movieId']))

# encode 'movieId'
films_to_films_encoded = dict(zip(films_ids, range(len(films_ids))))

# encoding index ke 'movieId'
films_encoded_to_films = dict(zip(range(len(films_ids)), films_ids))

"""Encode movieId"""

# Menambahkan kolom 'user' berdasarkan hasil encoding 'userId'
df.loc[:, 'user'] = df['userId'].apply(lambda x: user_to_user_encoded[x])

# Menambahkan kolom 'films' berdasarkan hasil encoding 'movieId'
df.loc[:, 'films'] = df['movieId'].apply(lambda x: films_to_films_encoded[x])

"""Tambahkan kolom encoded user dan film"""

# Menghitung jumlah user unik
num_users = df['user'].nunique()
print(num_users)

# Menghitung jumlah film unik
num_films = df['films'].nunique()
print(num_films)

# Mengubah tipe data rating menjadi float32
df['rating'] = df['rating'].astype('float32')

# Mengambil nilai rating minimum dan maksimum
min_rating = df['rating'].min()
max_rating = df['rating'].max()

# Menampilkan informasi jumlah user, film, dan nilai rating
print(f'Number of User: {num_users}, Number of Films: {num_films}, Min Rating: {min_rating}, Max Rating: {max_rating}')

"""Info jumlah user dan film"""

# sampling
df = df.sample(frac=1, random_state=42)
df

"""Shuffle data"""

from sklearn.model_selection import train_test_split

# Mengambil fitur user dan films
x = df[['user', 'films']].values

# Normalisasi rating ke rentang 0-1
y = df['rating'].apply(lambda r: (r - min_rating) / (max_rating - min_rating)).values

# Membagi data menjadi training dan validation dengan proporsi 80:20 secara acak
x_train, x_val, y_train, y_val = train_test_split(
    x, y, test_size=0.2, random_state=42, shuffle=True
)

print(x_train.shape, y_train.shape)
print(x_val.shape, y_val.shape)

"""Pisahkan fitur dan label

# content-based filtering
"""

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

class RecommenderNet(tf.keras.Model):

    def __init__(self, num_users, num_films, embedding_size, **kwargs):
        super().__init__(**kwargs)
        self.num_users = num_users
        self.num_films = num_films
        self.embedding_size = embedding_size

        # User embedding dan bias
        self.user_embedding = layers.Embedding(
            input_dim=num_users,
            output_dim=embedding_size,
            embeddings_initializer='he_normal',
            embeddings_regularizer=keras.regularizers.l2(1e-6)
        )
        self.user_bias = layers.Embedding(num_users, 1)

        # Film embedding dan bias
        self.films_embedding = layers.Embedding(
            input_dim=num_films,
            output_dim=embedding_size,
            embeddings_initializer='he_normal',
            embeddings_regularizer=keras.regularizers.l2(1e-6)
        )
        self.films_bias = layers.Embedding(num_films, 1)

    def call(self, inputs):
        user_vector = self.user_embedding(inputs[:, 0])
        user_bias = self.user_bias(inputs[:, 0])
        films_vector = self.films_embedding(inputs[:, 1])
        films_bias = self.films_bias(inputs[:, 1])

        # Menghitung hasil dot product antara user dan film embedding
        dot_product = tf.reduce_sum(user_vector * films_vector, axis=1, keepdims=True)

        # Menjumlahkan dot product dengan bias user dan film
        x = dot_product + user_bias + films_bias

        return tf.nn.sigmoid(x)

"""Buat arsitektur RecommenderNet"""

model = RecommenderNet(num_users, num_films, 50) # model initialization

# model compile
model.compile(
    loss = tf.keras.losses.BinaryCrossentropy(),
    optimizer = keras.optimizers.Adam(learning_rate=0.001),
    metrics=[tf.keras.metrics.RootMeanSquaredError()]
)

"""Kompilasi model"""

# Callback untuk early stopping (opsional)
from tensorflow.keras.callbacks import EarlyStopping
early_stop = EarlyStopping(monitor='val_loss', patience=3)

# Latih ulang model
history = model.fit(
    x = x_train,
    y = y_train,
    batch_size = 32,
    epochs = 50,
    validation_data = (x_val, y_val),
    callbacks=[early_stop]
)

"""Training model"""

# plot metrics evaluations
plt.plot(history.history['root_mean_squared_error'], color='blue')
plt.plot(history.history['val_root_mean_squared_error'], color='red')
plt.title('model_metrics')
plt.ylabel('root_mean_squared_error')
plt.xlabel('epoch')
plt.legend(['Train', 'Test'], loc='upper left')
plt.show()

"""Visualisasi evaluasi"""

# films
films_df = df_film
films_df.head()

"""Siapkan data film"""

# data ratings
df = films
df.head()

"""Gunakan dataframe utama"""

# Memilih user aktif (yang telah memberi rating ≥ 50)
user_counts = df.groupby('userId').size()
active_users = user_counts[user_counts >= 50].index.tolist()

# Check if active_users is empty
if not active_users:
    print("No active users found with 50 or more ratings in the filtered dataset.")
    # You might want to exit or handle this case appropriately,
    # depending on how you want to proceed when no such users exist.
    # For demonstration, we'll just print and skip the recommendation logic below.
else:
    # Mengambil satu user aktif secara acak
    user_id = np.random.choice(active_users)

    # Film yang sudah ditonton oleh user tersebut
    films_visited_by_user = df[df['userId'] == user_id]

    # Film yang belum ditonton user
    films_not_visited = films_df.loc[
        ~films_df['film_id'].isin(films_visited_by_user['movieId'].values), 'film_id'
    ]

    # Filter film yang ada dalam encoding
    films_not_visited = list(set(films_not_visited).intersection(set(films_to_films_encoded.keys())))

    # Buat list encoded film yang belum ditonton
    films_not_visited = [[films_to_films_encoded[x]] for x in films_not_visited]

    # Ambil encoded user
    user_encoder = user_to_user_encoded[user_id]

    # Buat array kombinasi user + film
    user_films_array = np.hstack((
        np.full((len(films_not_visited), 1), user_encoder),
        films_not_visited
    ))

    # --- The rest of your recommendation logic would go here, inside this else block ---
    # Prediksi rating film yang belum ditonton user
    ratings = model.predict(user_films_array).flatten()

    # Ambil indeks 10 rating tertinggi secara terbalik (descending)
    top_ratings_indices = np.argsort(ratings)[-10:][::-1]

    # Mapping indeks ke film_id asli
    recommended_films_ids = [films_encoded_to_films[films_not_visited[i][0]] for i in top_ratings_indices]

    print(f"Showing recommendations for users: {user_id}")
    print("===" * 9)
    print("Films with high ratings from user")
    print("----" * 8)

    # Ambil 5 film dengan rating tertinggi yang sudah ditonton user
    top_films_user = films_visited_by_user.sort_values(by='rating', ascending=False).head(5)['movieId'].values

    # Tampilkan nama dan genre film yang sudah ditonton
    for _, row in films_df[films_df['film_id'].isin(top_films_user)].iterrows():
        print(f"{row.film_name} : {row.genre}")

    print("----" * 8)
    print("Top 10 films recommendation")
    print("----" * 8)

    # Tampilkan rekomendasi film berdasarkan prediksi model
    for _, row in films_df[films_df['film_id'].isin(recommended_films_ids)].iterrows():
        print(f"{row.film_name} : {row.genre}")

"""Ambil satu user & prediksi film"""

# Prediksi rating film yang belum ditonton user
ratings = model.predict(user_films_array).flatten()

# Ambil indeks 10 rating tertinggi secara terbalik (descending)
top_ratings_indices = np.argsort(ratings)[-10:][::-1]

# Mapping indeks ke film_id asli
recommended_films_ids = [films_encoded_to_films[films_not_visited[i][0]] for i in top_ratings_indices]

print(f"Showing recommendations for users: {user_id}")
print("===" * 9)
print("Films with high ratings from user")
print("----" * 8)

# Ambil 5 film dengan rating tertinggi yang sudah ditonton user
top_films_user = films_visited_by_user.sort_values(by='rating', ascending=False).head(5)['movieId'].values

# Tampilkan nama dan genre film yang sudah ditonton
for _, row in films_df[films_df['film_id'].isin(top_films_user)].iterrows():
    print(f"{row.film_name} : {row.genre}")

print("----" * 8)
print("Top 10 films recommendation")
print("----" * 8)

# Tampilkan rekomendasi film berdasarkan prediksi model
for _, row in films_df[films_df['film_id'].isin(recommended_films_ids)].iterrows():
    print(f"{row.film_name} : {row.genre}")

"""Prediksi dan tampilkan rekomendasi"""

plt.plot(history.history['root_mean_squared_error'], color='blue')
plt.plot(history.history['val_root_mean_squared_error'], color='red')

# Plot RMSE dan Loss selama pelatihan
fig, ax = plt.subplots(1, 2, figsize=(14, 5))

# RMSE
ax[0].plot(history.history['root_mean_squared_error'], label='Train RMSE')
ax[0].plot(history.history['val_root_mean_squared_error'], label='Val RMSE')
ax[0].set_title('Root Mean Squared Error per Epoch')
ax[0].set_xlabel('Epoch')
ax[0].set_ylabel('RMSE')
ax[0].legend()

# Loss
ax[1].plot(history.history['loss'], label='Train Loss')
ax[1].plot(history.history['val_loss'], label='Val Loss')
ax[1].set_title('Binary Crossentropy Loss per Epoch')
ax[1].set_xlabel('Epoch')
ax[1].set_ylabel('Loss')
ax[1].legend()

plt.tight_layout()
plt.show()

"""Visualisasi RMSE dan Loss"""

def precision_at_k(recommended_ids, user_id, k=10):
    # Ambil semua film yang disukai user (rating >= 4)
    liked_by_user = df[(df['userId'] == user_id) & (df['rating'] >= 4)]['movieId'].values

    # Hitung berapa dari top-k rekomendasi yang termasuk dalam daftar liked_by_user
    hits = [film for film in recommended_ids[:k] if film in liked_by_user]
    precision = len(hits) / k

    print(f"Precision@{k}: {precision:.2f}")
    return precision

precision_at_k(recommended_films_ids, user_id, k=10)

"""Evaluasi Precision@k

# collaborative filtering
"""

class RecommenderNet(tf.keras.Model):
    def __init__(self, num_users, num_items, embedding_size):
        super().__init__()
        self.user_embedding = layers.Embedding(num_users, embedding_size)
        self.item_embedding = layers.Embedding(num_items, embedding_size)
        self.user_bias = layers.Embedding(num_users, 1)
        self.item_bias = layers.Embedding(num_items, 1)

    def call(self, inputs):
        user_vec = self.user_embedding(inputs[:, 0])
        item_vec = self.item_embedding(inputs[:, 1])
        dot = tf.reduce_sum(user_vec * item_vec, axis=1, keepdims=True)
        return tf.nn.sigmoid(dot + self.user_bias(inputs[:, 0]) + self.item_bias(inputs[:, 1]))

"""Arsitektur Model

"""

model.compile(
    loss=tf.keras.losses.BinaryCrossentropy(),
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
    metrics=[tf.keras.metrics.RootMeanSquaredError()]
)

history = model.fit(
    x_train, y_train,
    batch_size=32,
    epochs=50,
    validation_data=(x_val, y_val)
)

"""Pelatihan Model"""

# Plot RMSE dan Loss selama pelatihan
fig, ax = plt.subplots(1, 2, figsize=(14, 5))

# RMSE
ax[0].plot(history.history['root_mean_squared_error'], label='Train RMSE')
ax[0].plot(history.history['val_root_mean_squared_error'], label='Val RMSE')
ax[0].set_title('Root Mean Squared Error per Epoch')
ax[0].set_xlabel('Epoch')
ax[0].set_ylabel('RMSE')
ax[0].legend()

# Loss
ax[1].plot(history.history['loss'], label='Train Loss')
ax[1].plot(history.history['val_loss'], label='Val Loss')
ax[1].set_title('Binary Crossentropy Loss per Epoch')
ax[1].set_xlabel('Epoch')
ax[1].set_ylabel('Loss')
ax[1].legend()

plt.tight_layout()
plt.show()

"""Visualisasi RMSE dan Loss"""

# Pilih user aktif
user_counts = df.groupby('userId').size()
active_users = user_counts[user_counts >= 50].index.tolist()
user_id = np.random.choice(active_users)

# Film yang sudah ditonton oleh user tersebut
films_visited_by_user = df[df['userId'] == user_id]

# Film yang belum ditonton user
films_not_visited = films_df.loc[
    ~films_df['film_id'].isin(films_visited_by_user['movieId'].values), 'film_id'
]

films_not_visited = list(set(films_not_visited).intersection(set(films_to_films_encoded.keys())))
films_not_visited = [[films_to_films_encoded[x]] for x in films_not_visited]

user_encoder = user_to_user_encoded[user_id]
user_films_array = np.hstack((
    np.full((len(films_not_visited), 1), user_encoder),
    films_not_visited
))

""" Pilih User Aktif dan Prediksi"""

ratings = model.predict(user_films_array).flatten()
top_ratings_indices = np.argsort(ratings)[-10:][::-1]
recommended_films_ids = [films_encoded_to_films[films_not_visited[i][0]] for i in top_ratings_indices]

print(f"Rekomendasi untuk user {user_id}")
print("===" * 10)

print("5 Film yang disukai user:")
top_films_user = films_visited_by_user.sort_values(by='rating', ascending=False).head(5)['movieId'].values
for _, row in films_df[films_df['film_id'].isin(top_films_user)].iterrows():
    print(f"{row.film_name} : {row.genre}")

print("===" * 10)
print("10 Rekomendasi Teratas:")
for _, row in films_df[films_df['film_id'].isin(recommended_films_ids)].iterrows():
    print(f"{row.film_name} : {row.genre}")

"""Prediksi & Cetak Hasil Rekomendasi"""

def precision_at_k(recommended_ids, user_id, k=10):
    liked_by_user = df[(df['userId'] == user_id) & (df['rating'] >= 4)]['movieId'].values
    hits = [film for film in recommended_ids[:k] if film in liked_by_user]
    precision = len(hits) / k
    print(f"Precision@{k}: {precision:.2f}")
    return precision

precision_at_k(recommended_films_ids, user_id, k=10)

"""Precision@10"""